### PR TITLE
Add `spurt` as a CLI tool on install

### PR DESCRIPTION
**Pull request by scottstanie**
(Relies on the later PRs for `__main__.py` to exist)

This sets up `spurt` when you install the package:

```
$ pip install -e .
...
$ spurt --help
usage: spurt.workflows.emcf [-h] [--version] [-i INPUTDIR] [-o OUTPUTDIR] [--tempdir TEMPDIR] [-w WORKERS] [-b BATCHSIZE] [-c COH] [--singletile]

options:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -i INPUTDIR, --inputdir INPUTDIR
                        Input folder with phase-linked SLC stack. (default: None)
  -o OUTPUTDIR, --outputdir OUTPUTDIR
                        Output folder for final unwrapped raster files. (default: ./emcf)
  --tempdir TEMPDIR     Folder for intermediate outputs. (default: ./emcf_tmp)
  -w WORKERS, --workers WORKERS
                        Number of workers. <=0 uses ncpus - 1. (default: 0)
  -b BATCHSIZE, --batchsize BATCHSIZE
                        Links per batch for temporal unwrapping. (default: 50000)
  -c COH, --coh COH     Temporal coherence threshold for good pixels. (default: 0.6)
  --singletile          Process as a single tile. (default: False)
```

### CODE REVIEW

**Comment by piyushrpt** [comment]
Do we want to call this `spurt-emcf` instead of `spurt`? That way leaves room open for other pipelines and will be in line with things like `h5tools` or netcdf utilities.

**Comment by scottstanie** [comment]
Oh sure that's probably a good idea. I'd probably opt for doing subcommands like `spurt emcf ...` but both sound okay to me.

**Comment by piyushrpt** [comment]
subcommand works for me too. I will leave it up to you to pick either

**Comment by piyushrpt** [comment]
I have added this as `spurt-emcf` in `feat/dirichlet`. We can revisit this with subparsers / subcommands

**Pull request closed without merging**
