### PR TITLE
Reduce memory usage with futures

### PR DESCRIPTION
**Pull request by piyushrpt**
* Use dict and pop results from `ProcessPoolExecutor` futures
* Use `fork` explicitly with `ProcessPoolExecutor`

### CODE REVIEW

**Comment by scottstanie** [comment]
I did a small  `mprof run` test on my laptop with 9 tiles:  blue is the memory from this PR, black is main.
image
It does looks like it's slightly lower on average... actually pretty weird how large of a different in memory different some of the tiles showed. Not a huge difference in the peak.

**Comment by piyushrpt** [comment]
Are we worried about this `imap_unordered` call? 

https://github.com/isce-framework/spurt/blob/3a2ef2591cafdfddae0d28af3443701abbf40d6f/src/spurt/mcf/_ortools.py#L275

Usually very few links are unwrapped and these are really small.

**Comment by scottstanie** [comment]
hmm, comparing this one in black to the last version with `imap_unordered` in blue shows an increase in memory actually:
image


(the shorter runtime at the end was because i bumped up the merge parallelism. Theres only 7 dates here, and apparently merging all 15 interferograms at once doesn't even use as much memory as one of the spatial unwraps in each of the 9 tiles)

**Comment by piyushrpt** [comment]
Perfectly happy undoing the last commit and stashing it. I did not think it would have a noticable difference since very few links actually have non-zero residues.

**Comment by scottstanie** [comment]
I also realized i wasn't doing any parallel spatial unwrapping `--s-workers 1`, but was just setting imap unordered version with 3 parallel spatial unwrappings. Setting `--s-workers 3` with the `imap_unordered` one:
image

Now when I'm testing 3 unwraps at a time, there's actually not a big difference between `ProcessPoolExecutor` and `imap_unordered`
image

**Comment by scottstanie** [comment]
one thing we could add that I forgot to make a separate PR for: add the `chunksize` for the temporal unwrapping

```python
+++ b/src/spurt/mcf/_ortools.py
@@ -219,6 +219,7 @@ class ORMCFSolver(MCFSolverInterface):
         cost: np.ndarray,
         revcost: np.ndarray | None = None,
         worker_count: int | None = None,
+        chunksize: int | None = 1
     ) -> np.ndarray:
         """Parallel version of residues_to_flows.

@@ -273,7 +274,11 @@ class ORMCFSolver(MCFSolverInterface):
             # We explicitly use fork here as osx has switched to using spawn
             # and that really slows down the use of multiprocessing
             with get_context("fork").Pool(processes=worker_count) as p:
-                mp_tasks = p.imap_unordered(wrap_solve_mcf, uw_inputs(range(nruns)))
+                mp_tasks = p.imap_unordered(
+                    wrap_solve_mcf,
+                    uw_inputs(range(nruns)),
+                    # chunksize=chunksize
+                )

```

```
             flows = self._solver_time.residues_to_flows_many(
-                residues, cost, worker_count=self.settings.t_worker_count
+                residues, cost, worker_count=self.settings.t_worker_count, chunksize=50_000,
             )
```

**Review by scottstanie — APPROVED** [review]

**Pull request merged**
